# Generated by Django 4.1 on 2022-08-13 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 13, 0, 30, 35, 813053)),
        ),
    ]
