# Generated by Django 4.1 on 2022-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(default='It was a great trip', max_length=500),
            preserve_default=False,
        ),
    ]
