# Generated by Django 4.1 on 2022-08-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_trip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cityFrom',
            field=models.CharField(default='Home', max_length=50),
            preserve_default=False,
        ),
    ]
