# Generated by Django 4.1 on 2022-08-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_people_trip_peoples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='relation',
            field=models.CharField(choices=[('Family', 'Family'), ('Friend', 'Friend'), ('Spouse', 'Spouse'), ('Significant Other', 'Significant Other'), ('Other', 'Other')], default='Family', max_length=25),
        ),
    ]
